spring.application.name=ragapp
# ==========================================================
# CONFIGURAÇÕES GERAIS DA APLICAÇÃO
# ==========================================================
spring.application.name=easy-rag

# ==========================================================
# OPENAI CONFIGURATION (LANGCHAIN4J)
# ==========================================================

# 1. Configurações para o Modelo de Chat (LLM)
# Este é o modelo que gera as respostas finais 
# langchain4j.open-ai.chat-model.api-key=${OPENAI_API_KEY}
langchain4j.open-ai.chat-model.api-key=demo
langchain4j.open-ai.chat-model.model-name=gpt-4o-mini

# 2. Configurações para o Modelo de Embedding
# Este é o modelo que converte textos em vetores para busca (o tradutor)
langchain4j.open-ai.embedding-model.model-name=text-embedding-3-small